
adjective1 = input("Enter a adjective: ")
adjective2 = input("Enter another adjective: ")
bird = input("Name a type of bird: ")
room = input("Name a room in a house: ")
verb_past = input("Enter a past tense verb: ")
verb = input("Enter a verb: ")
realtive_name = input("Enter a relative's name: ")
noun = input("Enter a noun: ")
liquid = input("Name a liquid: ")
verb_ending = input("Name a verb ending in -ing: ")
part_of_body = input("Name a part of the body: ")
plural_noun = input("Enter a plural noun: ")
verb_ending2 = input("Enter a verb ending in -ing: ")
noun2 = input("Enter a noun: ")

print("It was a " + adjective1 + " cold November day. ")
print("I woke up to the " + adjective2 + " smell of " + bird + " roasting in the " + room + " downstairs. ")
print("I " + verb_past + " down the stairs to see if i could help " + verb + " the dinner")
print("My mom said, see if " + realtive_name + " needs a fresh " + noun + " .")
print("So I carried a tray of glasses full of " + liquid + " into the " + verb_ending + " room.")
print("When I got there, I couldn't believe my " + part_of_body + "! ")
print("There were " + plural_noun + " " + verb_ending2 + " on the " + noun2 + "! ")
print("---- This shit was made by Kla3 ----")
time.sleep(160)